### PR TITLE
Add Prism logo

### PR DESCRIPTION
**Pull request by martinwoodward**
Add the Prism logo to the Swag repo /cc @brianlagunas @briannoyes

### CODE REVIEW

**Comment by brianlagunas** [comment]
Sweet!  I will update the logo with the "sticker" version :)

**Comment by brianlagunas** [comment]
Oh, never mind, you already have the Prism_Logo_600.png that should be used for the stickers.

**Comment by martinwoodward** [comment]
Prism_logo_hi.png is a good one printing as well. That's 3000px so can go up to 10" with that on some merchandise without the image going blocky

**Comment by martinwoodward** [comment]
If you are happy - I'll get some stickers ordered up so you can hand them out at Build

**Comment by brianlagunas** [comment]
Definitely!  Let's do it!

**Pull request merged**
