### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OmarElabd**

### CODE REVIEW

**Comment by martinwoodward** [comment]
Thanks Omar!

**Comment by OmarElabd** [comment]
My pleasure, that might be the smallest pull request possible though :)

**Comment by BethMassi** [comment]
@OmarElabd small but important!

**Comment by martinwoodward** [comment]
Just like me (well 50% of that is definitely true ;-) )

**Comment by BethMassi** [comment]
:+1:

**Pull request merged**
