### PR TITLE
Add dotnet-bot images

### PR DESCRIPTION
**Pull request by richlander**
- This is the avatar image for @dotnet-bot
- Several variations are provided

### CODE REVIEW

**Comment by martinwoodward** [comment]
Nice!  Would you also be able to add a PNG of "dotnet-bot-ascii-pot-small.png" that is 500px big (i.e. exactly 2x the size used in the README.md). That way IE will do a better job of rendering a preview of the image but it will still look nice for folks with many retina macbooks like you?

**Comment by terrajobst** [comment]
Will do.

**Comment by martinwoodward** [comment]
Which image do we want turning into a sticker for the SWAG store? dotnet-bot-ascii-pot.png or dotnet-bot-pot.png

**Comment by terrajobst** [comment]
I'd go with dotnet-bot-pot.png because we've tried the ASCII art based versions before and they don't print well on shirts. Now, it's probably fine for stickers or cups but it seems consistency makes a bit more sense.

@richlander @martinwoodward?

**Comment by martinwoodward** [comment]
I'm tempted to try a pack of each and see if the ASCII one turns out, but it's quite an expensive experiment. Speaking of ASCII - in the ASCII versions there is a rouge "-" in between the legs (close to the right foot) that will mess up the borders of die-cut stickers and now I've seen it I'm having trouble un-seeing it.  Would you be able to remove that too (sorry).  I'm happy to do that as a fresh PR if you wanted.

**Comment by terrajobst** [comment]
> in the ASCII versions there is a rouge "-" in between the legs

Eagle eye! I didn't see that earlier. Will fix and send you the updated version.

**Comment by richlander** [comment]
Am I supposed to do something? Should I switch the specific image used in the readme.md?

**Comment by martinwoodward** [comment]
I think this is the remaining work:

 - [ ] Replace ascii art versions with a version that doesn't have the rouge "-" in it
 - [ ] Add a 500px version of preview image
 - [ ] Reference the preview image in the ReadMe.md (specifying 250 width)
 - [ ] Update PR and I'll get some stickers put into the market place and start work on other swag

**Comment by terrajobst** [comment]
Thanks @martinwoodward. I really like the check-list style. I've clicked the ones that I feel are done. Not sure about the stickers, though.

**Comment by richlander** [comment]
We can now merge, right? Feel free to merge instead of answering.

**Comment by terrajobst** [comment]
Sounds good to me.

**Comment by martinwoodward** [comment]
Ordered a version of the ascii bot scaled down for a 3" sticker at 300dpi. We'll wait to see what it comes out like first before placing in the swag store. Should be with you guys around July 1st

**Pull request merged**
