### PR TITLE
Add IdentityServer artwork

### PR DESCRIPTION
**Pull request by leastprivilege**

### CODE REVIEW

**Comment by martinwoodward** [comment]
I'll look at creating some Hi-res versions from this as the artwork wouldn't be big enough for a good sticker or putting on a mug yet.

**Comment by leastprivilege** [comment]
That's why I asked you what we need ;) I can get other resolutions - I just didn't know what exactly to ask for.

**Comment by martinwoodward** [comment]
Ah great - I just did a [Vector version in Illustrator](https://1drv.ms/u/s!AnoZDWDiiqDHxd4byYkzj7W5WPhnXw) but if the person that created this already did it in a vector format that would probably be better.

If they don't have a Vector version (SVG, AI, EPS or PDF format etc) then feel free to add the one linked above into the PR.

**Comment by leastprivilege** [comment]
@brockallen have a look please.

**Comment by leastprivilege** [comment]
I added PSD and EPS file - especially the EPS file has the logo and the text. Does that work?

**Comment by martinwoodward** [comment]
Thanks!

**Pull request merged**
