### PR TITLE
Roslyn Swag Submission

### PR DESCRIPTION
**Pull request by kuhlenh**
Submitting my design for the [Roslyn project](https://github.com/dotnet/roslyn). Feel free to use my raw files to tweak the design or iterate on my design.

Also changed the readme to table layout for readability. 
roslynlogo

### CODE REVIEW

**Comment by BethMassi** [comment]
LGTM

**Comment by kenegozi** [comment]
Looks Great To Me

**Comment by JoshVarty** [comment]
:+1:

**Comment by paulbouwer** [comment]
:+1: I like it !

**Comment by martinwoodward** [comment]
:sparkles: Love it - thanks!

**Pull request merged**
